name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'fe/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'fe/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fe

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './fe/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check code style
        run: npm run lint
        
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: fe/dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build
